name: Build

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
      - '.github/**'
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ '8', '11', '17' ]

    steps:
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Europe/Zurich

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Java ${{ matrix.Java }} JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          architecture: x64
          cache: 'gradle'
          check-latest: true

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Cache Gradle packages
        uses: actions/cache@v2.1.7
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew build --warn --full-stacktrace

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-libs-java-${{ matrix.Java }}
          path: build/libs
          retention-days: 90
