name: Delete old workflow runs
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  delete_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write

    steps:
      - name: Setup timezone
        run: |
          sudo timedatectl set-timezone Europe/Zurich
          timedatectl

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 30
          keep_minimum_runs: 7