name: Publish

on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  publish:
    name: Publish Release Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Europe/Zurich

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Java 8 JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 8
          architecture: x64
          cache: 'gradle'
          check-latest: true

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Decode GPG Key
        run: |
          echo "${{secrets.SIGNING_SECRET_KEY_RING_FILE}}" > ~/.gradle/secring.gpg.b64
          base64 -d ~/.gradle/secring.gpg.b64 > ~/.gradle/secring.gpg

      - name: Publish package
        run: ./gradlew publish -Psigning.keyId=${{secrets.SIGNING_KEY_ID}} -Psigning.password=${{secrets.SIGNING_PASSWORD}} -Psigning.secretKeyRingFile=$(echo ~/.gradle/secring.gpg) --warn --full-stacktrace
        env:
          OSSRH_USERNAME: ${{secrets.OSSRH_USERNAME}}
          OSSRH_PASSWORD: ${{secrets.OSSRH_PASSWORD}}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release-build-libs
          path: build/libs
          retention-days: 90