name: Publish package to the Maven Central Repository
on:
  workflow_dispatch:
#  release:
#    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Europe/Zurich

      - name: Check out the repo
        uses: actions/checkout@v2.4.0

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
          architecture: x64

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Publish package
        run: ./gradlew publish --warn --stacktrace